### ISSUE TITLE
请问如下报错是什么原因？有git在环境变量里

### ISSUE THREAD

**Issue by al4n233** [BugScanTeam/GitHack#9]
python GitHack.py http://38a281f9-b9fd-4833-a0db-bd3e3d297ec8.node3.buuoj.cn/.git
Traceback (most recent call last):
  File "GitHack.py", line 11, in <module>
    from lib.common import banner
  File "D:\GitHack-master\lib\common.py", line 84
    except IOError, ex:
                  ^
SyntaxError: invalid syntax

**Comment by Medicean** [comment]
你怕不是在用 Python3 哟

**Comment by HB6H057** [comment]
也是醉了，还得弄个python2
